import Flutter
import UIKit

@main
@objc class AppDelegate: FlutterAppDelegate, FlutterImplicitEngineDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  func didInitializeImplicitFlutterEngine(_ engineBridge: FlutterImplicitEngineBridge) {
    GeneratedPluginRegistrant.register(with: engineBridge.pluginRegistry)

    // Wires the IDEMIA bridge to the engine's channel. `setUp` is generated by
    // Pigeon (see `IdemiaCardApi.g.swift`) — it registers one `FlutterMethodChannel`
    // per HostApi method under the hood, so nothing here talks MethodChannel
    // directly.
    let messenger = engineBridge.applicationRegistrar.messenger()
    IdemiaCardHostApiSetup.setUp(binaryMessenger: messenger, api: IdemiaCardBridge())
    WalletExtensionSimulatorHostApiSetup.setUp(binaryMessenger: messenger, api: ExtensionSimulatorBridge())
  }
}
