import Flutter
import UIKit

@main
@objc class AppDelegate: FlutterAppDelegate, FlutterImplicitEngineDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  func didInitializeImplicitFlutterEngine(_ engineBridge: FlutterImplicitEngineBridge) {
    GeneratedPluginRegistrant.register(with: engineBridge.pluginRegistry)

    // Wires the card-tokenization bridge to the engine's channel. `setUp` is generated by
    // Pigeon (see `CardTokenizationApi.g.swift`) — it registers one `FlutterMethodChannel`
    // per HostApi method under the hood, so nothing here talks MethodChannel
    // directly.
    let messenger = engineBridge.applicationRegistrar.messenger()
    CardTokenizationHostApiSetup.setUp(binaryMessenger: messenger, api: CardTokenizationBridge())
    WalletExtensionSimulatorHostApiSetup.setUp(binaryMessenger: messenger, api: ExtensionSimulatorBridge())
    SecureCardDisplayHostApiSetup.setUp(binaryMessenger: messenger, api: SecureCardDisplayBridge())

    engineBridge.applicationRegistrar.register(
      SecureCardDisplayPlatformViewFactory(),
      withId: "secure_card_display_view"
    )
  }
}
