// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum IdemiaCardApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Contract for the IDEMIA Digital Card SDK bridge.
///
/// ## Why this shape, not a 1:1 mirror of the Swift SDK
///
/// The real SDK's `startPushProvisioning` takes a `ProvisioningData` whose
/// `handler` field is a Swift **closure** that receives a `PKAddPaymentPassRequest`
/// and drives the native `PKAddPaymentPassViewController`. A closure cannot
/// cross a Pigeon boundary — there is no Dart representation of "a callback the
/// native side invokes with a native-only PassKit object".
///
/// So the boundary is drawn one level higher: Flutter hands over everything the
/// *bank's backend* supplied (certificates, nonce, the signed JWS) and asks for
/// a plain success/failure. Presenting `PKAddPaymentPassViewController` and
/// wiring the SDK's handler closure happens entirely inside the native
/// implementation — see `IdemiaCardBridge.swift`. This is the same principle as
/// `ApiClient` not leaking `DioException`: each layer speaks its own
/// vocabulary, and the translation lives at the seam, not in the caller.
///
/// GENERATED: `lib/core/native/idemia_card_api.g.dart` and
/// `ios/Runner/IdemiaCardApi.g.swift` — regenerate with:
///   dart run pigeon --input pigeons/idemia_card_api.dart
///
/// Generated class from Pigeon that represents data sent in messages.
struct CardHandleData: Hashable, CustomStringConvertible {
  var cardHandle: String
  var issuerId: String
  var lastDigits: String
  var expiry: String
  /// `ACTIVE` / `NOT_ACTIVE` / `SUSPENDED` / `TERMINATED` — kept as the raw
  /// string from the SDK's `CardState`. Decoding into a Dart enum happens on
  /// the Flutter side, in the same mapper that already parses `CardDto.state`,
  /// so there is exactly one place that knows the four values.
  var state: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CardHandleData? {
    let cardHandle = pigeonVar_list[0] as! String
    let issuerId = pigeonVar_list[1] as! String
    let lastDigits = pigeonVar_list[2] as! String
    let expiry = pigeonVar_list[3] as! String
    let state = pigeonVar_list[4] as! String

    return CardHandleData(
      cardHandle: cardHandle,
      issuerId: issuerId,
      lastDigits: lastDigits,
      expiry: expiry,
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      cardHandle,
      issuerId,
      lastDigits,
      expiry,
      state,
    ]
  }
  static func == (lhs: CardHandleData, rhs: CardHandleData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return IdemiaCardApiPigeonInternal.deepEquals(lhs.cardHandle, rhs.cardHandle) && IdemiaCardApiPigeonInternal.deepEquals(lhs.issuerId, rhs.issuerId) && IdemiaCardApiPigeonInternal.deepEquals(lhs.lastDigits, rhs.lastDigits) && IdemiaCardApiPigeonInternal.deepEquals(lhs.expiry, rhs.expiry) && IdemiaCardApiPigeonInternal.deepEquals(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CardHandleData")
    IdemiaCardApiPigeonInternal.deepHash(value: cardHandle, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: issuerId, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: lastDigits, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: expiry, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: state, hasher: &hasher)
  }

  public var description: String {
    return "CardHandleData(cardHandle: \(String(describing: cardHandle)), issuerId: \(String(describing: issuerId)), lastDigits: \(String(describing: lastDigits)), expiry: \(String(describing: expiry)), state: \(String(describing: state)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProvisionableCard: Hashable, CustomStringConvertible {
  var cardReferenceId: String
  var issuerId: String
  var lastDigits: String
  var expiry: String
  var paymentNetwork: String
  var displayName: String
  /// One of the SDK's `Eligibility` raw values: `eligible`, `nonEligible`,
  /// `alreadyProvisioned`, `alreadyProvisionedOnPhone`, `alreadyProvisionedOnWatch`.
  var eligibilityStatus: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProvisionableCard? {
    let cardReferenceId = pigeonVar_list[0] as! String
    let issuerId = pigeonVar_list[1] as! String
    let lastDigits = pigeonVar_list[2] as! String
    let expiry = pigeonVar_list[3] as! String
    let paymentNetwork = pigeonVar_list[4] as! String
    let displayName = pigeonVar_list[5] as! String
    let eligibilityStatus = pigeonVar_list[6] as! String

    return ProvisionableCard(
      cardReferenceId: cardReferenceId,
      issuerId: issuerId,
      lastDigits: lastDigits,
      expiry: expiry,
      paymentNetwork: paymentNetwork,
      displayName: displayName,
      eligibilityStatus: eligibilityStatus
    )
  }
  func toList() -> [Any?] {
    return [
      cardReferenceId,
      issuerId,
      lastDigits,
      expiry,
      paymentNetwork,
      displayName,
      eligibilityStatus,
    ]
  }
  static func == (lhs: ProvisionableCard, rhs: ProvisionableCard) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return IdemiaCardApiPigeonInternal.deepEquals(lhs.cardReferenceId, rhs.cardReferenceId) && IdemiaCardApiPigeonInternal.deepEquals(lhs.issuerId, rhs.issuerId) && IdemiaCardApiPigeonInternal.deepEquals(lhs.lastDigits, rhs.lastDigits) && IdemiaCardApiPigeonInternal.deepEquals(lhs.expiry, rhs.expiry) && IdemiaCardApiPigeonInternal.deepEquals(lhs.paymentNetwork, rhs.paymentNetwork) && IdemiaCardApiPigeonInternal.deepEquals(lhs.displayName, rhs.displayName) && IdemiaCardApiPigeonInternal.deepEquals(lhs.eligibilityStatus, rhs.eligibilityStatus)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProvisionableCard")
    IdemiaCardApiPigeonInternal.deepHash(value: cardReferenceId, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: issuerId, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: lastDigits, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: expiry, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: paymentNetwork, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: displayName, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: eligibilityStatus, hasher: &hasher)
  }

  public var description: String {
    return "ProvisionableCard(cardReferenceId: \(String(describing: cardReferenceId)), issuerId: \(String(describing: issuerId)), lastDigits: \(String(describing: lastDigits)), expiry: \(String(describing: expiry)), paymentNetwork: \(String(describing: paymentNetwork)), displayName: \(String(describing: displayName)), eligibilityStatus: \(String(describing: eligibilityStatus)))"
  }
}

/// Everything the bank's backend must supply before provisioning can start.
///
/// Every field here traces to a specific requirement in the bank's technical
/// spec (see the `assetHash`/JWS/certificate walkthrough): the wrapper does no
/// cryptography of its own, it only carries what the backend already signed.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ProvisioningRequest: Hashable, CustomStringConvertible {
  var cardReferenceId: String
  /// DER-encoded certificate chain, as the SDK's `ProvisioningData.certificates`
  /// expects (`[Data]` on the Swift side).
  var certificates: [FlutterStandardTypedData]
  var nonce: FlutterStandardTypedData
  var nonceSignature: FlutterStandardTypedData
  /// The JWS token (`enrollAuth`) signed by the bank's backend with its RSA
  /// private key — becomes `ProvisioningData.userAuthorization`.
  var userAuthorization: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProvisioningRequest? {
    let cardReferenceId = pigeonVar_list[0] as! String
    let certificates = pigeonVar_list[1] as! [FlutterStandardTypedData]
    let nonce = pigeonVar_list[2] as! FlutterStandardTypedData
    let nonceSignature = pigeonVar_list[3] as! FlutterStandardTypedData
    let userAuthorization = pigeonVar_list[4] as! String

    return ProvisioningRequest(
      cardReferenceId: cardReferenceId,
      certificates: certificates,
      nonce: nonce,
      nonceSignature: nonceSignature,
      userAuthorization: userAuthorization
    )
  }
  func toList() -> [Any?] {
    return [
      cardReferenceId,
      certificates,
      nonce,
      nonceSignature,
      userAuthorization,
    ]
  }
  static func == (lhs: ProvisioningRequest, rhs: ProvisioningRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return IdemiaCardApiPigeonInternal.deepEquals(lhs.cardReferenceId, rhs.cardReferenceId) && IdemiaCardApiPigeonInternal.deepEquals(lhs.certificates, rhs.certificates) && IdemiaCardApiPigeonInternal.deepEquals(lhs.nonce, rhs.nonce) && IdemiaCardApiPigeonInternal.deepEquals(lhs.nonceSignature, rhs.nonceSignature) && IdemiaCardApiPigeonInternal.deepEquals(lhs.userAuthorization, rhs.userAuthorization)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProvisioningRequest")
    IdemiaCardApiPigeonInternal.deepHash(value: cardReferenceId, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: certificates, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: nonce, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: nonceSignature, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: userAuthorization, hasher: &hasher)
  }

  public var description: String {
    return "ProvisioningRequest(cardReferenceId: \(String(describing: cardReferenceId)), certificates: \(String(describing: certificates)), nonce: \(String(describing: nonce)), nonceSignature: \(String(describing: nonceSignature)), userAuthorization: \(String(describing: userAuthorization)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProvisioningResult: Hashable, CustomStringConvertible {
  var success: Bool
  /// A code from Appendix A of the bank's spec (`CARD_EXPIRED`, `CARD_LOCKED`,
  /// …) when the SDK or PassKit rejected the request. `null` on success.
  var errorCode: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProvisioningResult? {
    let success = pigeonVar_list[0] as! Bool
    let errorCode: String? = nilOrValue(pigeonVar_list[1])
    let errorMessage: String? = nilOrValue(pigeonVar_list[2])

    return ProvisioningResult(
      success: success,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: ProvisioningResult, rhs: ProvisioningResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return IdemiaCardApiPigeonInternal.deepEquals(lhs.success, rhs.success) && IdemiaCardApiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && IdemiaCardApiPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProvisioningResult")
    IdemiaCardApiPigeonInternal.deepHash(value: success, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    IdemiaCardApiPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "ProvisioningResult(success: \(String(describing: success)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)))"
  }
}

private class IdemiaCardApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CardHandleData.fromList(self.readValue() as! [Any?])
    case 130:
      return ProvisionableCard.fromList(self.readValue() as! [Any?])
    case 131:
      return ProvisioningRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return ProvisioningResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class IdemiaCardApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CardHandleData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ProvisionableCard {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ProvisioningRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ProvisioningResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class IdemiaCardApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return IdemiaCardApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return IdemiaCardApiPigeonCodecWriter(data: data)
  }
}

class IdemiaCardApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = IdemiaCardApiPigeonCodec(readerWriter: IdemiaCardApiPigeonCodecReaderWriter())
}


/// Methods Flutter calls; the Swift side implements them.
///
/// `@async` marks a method as `async` on both sides — Pigeon generates a
/// `Future`-returning Dart method backed by a Swift method using completion
/// handlers (or `async`/`await`, matching the SDK's own signatures almost
/// exactly, since the SDK itself is already async-first).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IdemiaCardHostApi {
  func findCardsByCardHolder(cardHolderHandle: String, issuerId: String, completion: @escaping (Result<[CardHandleData], Error>) -> Void)
  func checkCards(issuerId: String, cardHandles: [String], completion: @escaping (Result<[ProvisionableCard], Error>) -> Void)
  /// Synchronous in the real SDK (`canAddCards` has no `async` keyword there)
  /// because it only reads local PassKit state — no network round trip, so no
  /// reason to force it through the async machinery on either side.
  func canAddCards(lastDigits: [String]) throws -> [String: String]
  /// Presents `PKAddPaymentPassViewController` natively and drives it to
  /// completion. The `Future` resolves only after the user finishes the native
  /// flow (or cancels/fails it) — this single call replaces
  /// `generatePassKitRequestConfiguration` + `startPushProvisioning` +
  /// `notifyProvisioningCompleted` from the raw SDK, because all three only
  /// make sense chained together on the native side.
  func startProvisioning(request: ProvisioningRequest, completion: @escaping (Result<ProvisioningResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IdemiaCardHostApiSetup {
  static var codec: FlutterStandardMessageCodec { IdemiaCardApiPigeonCodec.shared }
  /// Sets up an instance of `IdemiaCardHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IdemiaCardHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let findCardsByCardHolderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.IdemiaCardHostApi.findCardsByCardHolder\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      findCardsByCardHolderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cardHolderHandleArg = args[0] as! String
        let issuerIdArg = args[1] as! String
        api.findCardsByCardHolder(cardHolderHandle: cardHolderHandleArg, issuerId: issuerIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      findCardsByCardHolderChannel.setMessageHandler(nil)
    }
    let checkCardsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.IdemiaCardHostApi.checkCards\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkCardsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let issuerIdArg = args[0] as! String
        let cardHandlesArg = args[1] as! [String]
        api.checkCards(issuerId: issuerIdArg, cardHandles: cardHandlesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkCardsChannel.setMessageHandler(nil)
    }
    /// Synchronous in the real SDK (`canAddCards` has no `async` keyword there)
    /// because it only reads local PassKit state — no network round trip, so no
    /// reason to force it through the async machinery on either side.
    let canAddCardsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.IdemiaCardHostApi.canAddCards\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canAddCardsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let lastDigitsArg = args[0] as! [String]
        do {
          let result = try api.canAddCards(lastDigits: lastDigitsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      canAddCardsChannel.setMessageHandler(nil)
    }
    /// Presents `PKAddPaymentPassViewController` natively and drives it to
    /// completion. The `Future` resolves only after the user finishes the native
    /// flow (or cancels/fails it) — this single call replaces
    /// `generatePassKitRequestConfiguration` + `startPushProvisioning` +
    /// `notifyProvisioningCompleted` from the raw SDK, because all three only
    /// make sense chained together on the native side.
    let startProvisioningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.IdemiaCardHostApi.startProvisioning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startProvisioningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ProvisioningRequest
        api.startProvisioning(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startProvisioningChannel.setMessageHandler(nil)
    }
  }
}
