// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum SecureCardDisplayApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class SecureCardDisplayApiPigeonCodecReader: FlutterStandardReader {
}

private class SecureCardDisplayApiPigeonCodecWriter: FlutterStandardWriter {
}

private class SecureCardDisplayApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SecureCardDisplayApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SecureCardDisplayApiPigeonCodecWriter(data: data)
  }
}

class SecureCardDisplayApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SecureCardDisplayApiPigeonCodec(readerWriter: SecureCardDisplayApiPigeonCodecReaderWriter())
}


/// Contract for the lifecycle of IDEMIA's `CardSecureDisplay` module (see
/// section 5.2 of the bank's IDEMIA SDK spec).
///
/// ## Why no method here returns the rendered image
///
/// The whole point of `CardSecureDisplay` is that the full PAN/PIN never
/// exists as text or bytes any caller can log, cache, or ship elsewhere.
/// Returning image bytes across this API would put pixel data of a secret
/// value into Dart memory — technically not the PAN as a string, but still
/// a needless copy of sensitive material crossing a boundary that does not
/// need it to cross.
///
/// Instead, rendering happens entirely on the native side, inside a
/// `FlutterPlatformView` (`SecureCardDisplayPlatformView.swift`) that calls
/// `FakeSecureCardDisplayService.getCardDataImage`/`getCardPinImage`
/// directly and shows the result in a native `UIImageView`. Flutter only
/// ever asks for the *view* (via `UiKitView`), never the image data — the
/// same "hand over a native view, not bytes" principle already used for
/// `PKAddPaymentPassViewController` in `IdemiaCardBridge`.
///
/// This file therefore only covers what genuinely needs Dart-side control:
/// the module's lifecycle (`initialize`/`wipe`) and the one method whose
/// result — a system pasteboard write — has no visual representation for a
/// platform view to own.
///
/// GENERATED: `lib/core/native/secure_card_display_api.g.dart` and
/// `ios/Runner/SecureCardDisplayApi.g.swift` — regenerate with:
///   dart run pigeon --input pigeons/secure_card_display_api.dart
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SecureCardDisplayHostApi {
  func initialize(completion: @escaping (Result<Void, Error>) -> Void)
  func isInitialized(completion: @escaping (Result<Bool, Error>) -> Void)
  func copyPanToClipboard(cardReferenceId: String, ttlSeconds: Double, completion: @escaping (Result<Void, Error>) -> Void)
  func wipe(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SecureCardDisplayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { SecureCardDisplayApiPigeonCodec.shared }
  /// Sets up an instance of `SecureCardDisplayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SecureCardDisplayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.SecureCardDisplayHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        api.initialize { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let isInitializedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.SecureCardDisplayHostApi.isInitialized\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isInitializedChannel.setMessageHandler { _, reply in
        api.isInitialized { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isInitializedChannel.setMessageHandler(nil)
    }
    let copyPanToClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.SecureCardDisplayHostApi.copyPanToClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      copyPanToClipboardChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cardReferenceIdArg = args[0] as! String
        let ttlSecondsArg = args[1] as! Double
        api.copyPanToClipboard(cardReferenceId: cardReferenceIdArg, ttlSeconds: ttlSecondsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      copyPanToClipboardChannel.setMessageHandler(nil)
    }
    let wipeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.SecureCardDisplayHostApi.wipe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      wipeChannel.setMessageHandler { _, reply in
        api.wipe { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      wipeChannel.setMessageHandler(nil)
    }
  }
}
