// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum WalletExtensionSimulatorApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// A debug-only channel to the Wallet Extension's logic, called directly by
/// our own UI instead of by the real Apple Wallet.
///
/// This is intentionally a **separate** Pigeon file from `card_tokenization_api.dart`:
/// that one describes production API surface (what the app calls to talk to
/// the SDK); this one describes a test harness that will not exist once real
/// device testing with the issuer entitlement is possible. Keeping them apart
/// means deleting the harness later is a two-file removal, not a search for
/// which methods in a shared file were "the real ones."
///
/// Generated class from Pigeon that represents data sent in messages.
struct ExtensionStatusResult: Hashable, CustomStringConvertible {
  var passEntriesAvailable: Bool
  var requiresAuthentication: Bool
  /// Measured natively, around the exact call the real Wallet times against
  /// its ~100ms budget — see `ExtensionSimulatorBridge.simulateStatus`. Kept
  /// as a plain int rather than a `Duration` because Pigeon has no `Duration`
  /// type; the Dart side converts it back.
  var elapsedMicroseconds: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExtensionStatusResult? {
    let passEntriesAvailable = pigeonVar_list[0] as! Bool
    let requiresAuthentication = pigeonVar_list[1] as! Bool
    let elapsedMicroseconds = pigeonVar_list[2] as! Int64

    return ExtensionStatusResult(
      passEntriesAvailable: passEntriesAvailable,
      requiresAuthentication: requiresAuthentication,
      elapsedMicroseconds: elapsedMicroseconds
    )
  }
  func toList() -> [Any?] {
    return [
      passEntriesAvailable,
      requiresAuthentication,
      elapsedMicroseconds,
    ]
  }
  static func == (lhs: ExtensionStatusResult, rhs: ExtensionStatusResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return WalletExtensionSimulatorApiPigeonInternal.deepEquals(lhs.passEntriesAvailable, rhs.passEntriesAvailable) && WalletExtensionSimulatorApiPigeonInternal.deepEquals(lhs.requiresAuthentication, rhs.requiresAuthentication) && WalletExtensionSimulatorApiPigeonInternal.deepEquals(lhs.elapsedMicroseconds, rhs.elapsedMicroseconds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ExtensionStatusResult")
    WalletExtensionSimulatorApiPigeonInternal.deepHash(value: passEntriesAvailable, hasher: &hasher)
    WalletExtensionSimulatorApiPigeonInternal.deepHash(value: requiresAuthentication, hasher: &hasher)
    WalletExtensionSimulatorApiPigeonInternal.deepHash(value: elapsedMicroseconds, hasher: &hasher)
  }

  public var description: String {
    return "ExtensionStatusResult(passEntriesAvailable: \(String(describing: passEntriesAvailable)), requiresAuthentication: \(String(describing: requiresAuthentication)), elapsedMicroseconds: \(String(describing: elapsedMicroseconds)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PassEntryData: Hashable, CustomStringConvertible {
  var cardReferenceId: String
  var displayName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PassEntryData? {
    let cardReferenceId = pigeonVar_list[0] as! String
    let displayName = pigeonVar_list[1] as! String

    return PassEntryData(
      cardReferenceId: cardReferenceId,
      displayName: displayName
    )
  }
  func toList() -> [Any?] {
    return [
      cardReferenceId,
      displayName,
    ]
  }
  static func == (lhs: PassEntryData, rhs: PassEntryData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return WalletExtensionSimulatorApiPigeonInternal.deepEquals(lhs.cardReferenceId, rhs.cardReferenceId) && WalletExtensionSimulatorApiPigeonInternal.deepEquals(lhs.displayName, rhs.displayName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PassEntryData")
    WalletExtensionSimulatorApiPigeonInternal.deepHash(value: cardReferenceId, hasher: &hasher)
    WalletExtensionSimulatorApiPigeonInternal.deepHash(value: displayName, hasher: &hasher)
  }

  public var description: String {
    return "PassEntryData(cardReferenceId: \(String(describing: cardReferenceId)), displayName: \(String(describing: displayName)))"
  }
}

private class WalletExtensionSimulatorApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ExtensionStatusResult.fromList(self.readValue() as! [Any?])
    case 130:
      return PassEntryData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class WalletExtensionSimulatorApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ExtensionStatusResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PassEntryData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class WalletExtensionSimulatorApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WalletExtensionSimulatorApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WalletExtensionSimulatorApiPigeonCodecWriter(data: data)
  }
}

class WalletExtensionSimulatorApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WalletExtensionSimulatorApiPigeonCodec(readerWriter: WalletExtensionSimulatorApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WalletExtensionSimulatorHostApi {
  /// Instantiates `ServiceProvider` (the same class the real extension uses)
  /// and calls `status(completion:)` directly — a plain method call, not a
  /// system-routed one — timing it the way Wallet's own 100ms budget would.
  func simulateStatus(completion: @escaping (Result<ExtensionStatusResult, Error>) -> Void)
  /// `LAContext.evaluatePolicy` with Face ID/Touch ID — the same
  /// authentication gate `requiresAuthentication` would trigger for a real
  /// UI Extension, run here as a plain call from the main app instead of a
  /// second `.appex` process.
  func authenticate(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Calls `ServiceProvider.passEntries(completion:)` directly, mapping the
  /// resulting `PKIssuerProvisioningExtensionPassEntry` array to plain data.
  func simulatePassEntries(completion: @escaping (Result<[PassEntryData], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WalletExtensionSimulatorHostApiSetup {
  static var codec: FlutterStandardMessageCodec { WalletExtensionSimulatorApiPigeonCodec.shared }
  /// Sets up an instance of `WalletExtensionSimulatorHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WalletExtensionSimulatorHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Instantiates `ServiceProvider` (the same class the real extension uses)
    /// and calls `status(completion:)` directly — a plain method call, not a
    /// system-routed one — timing it the way Wallet's own 100ms budget would.
    let simulateStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.WalletExtensionSimulatorHostApi.simulateStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      simulateStatusChannel.setMessageHandler { _, reply in
        api.simulateStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      simulateStatusChannel.setMessageHandler(nil)
    }
    /// `LAContext.evaluatePolicy` with Face ID/Touch ID — the same
    /// authentication gate `requiresAuthentication` would trigger for a real
    /// UI Extension, run here as a plain call from the main app instead of a
    /// second `.appex` process.
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.WalletExtensionSimulatorHostApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { _, reply in
        api.authenticate { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
    /// Calls `ServiceProvider.passEntries(completion:)` directly, mapping the
    /// resulting `PKIssuerProvisioningExtensionPassEntry` array to plain data.
    let simulatePassEntriesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bank_app_reference.WalletExtensionSimulatorHostApi.simulatePassEntries\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      simulatePassEntriesChannel.setMessageHandler { _, reply in
        api.simulatePassEntries { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      simulatePassEntriesChannel.setMessageHandler(nil)
    }
  }
}
