// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Contract for the IDEMIA Digital Card SDK bridge.
///
/// ## Why this shape, not a 1:1 mirror of the Swift SDK
///
/// The real SDK's `startPushProvisioning` takes a `ProvisioningData` whose
/// `handler` field is a Swift **closure** that receives a `PKAddPaymentPassRequest`
/// and drives the native `PKAddPaymentPassViewController`. A closure cannot
/// cross a Pigeon boundary — there is no Dart representation of "a callback the
/// native side invokes with a native-only PassKit object".
///
/// So the boundary is drawn one level higher: Flutter hands over everything the
/// *bank's backend* supplied (certificates, nonce, the signed JWS) and asks for
/// a plain success/failure. Presenting `PKAddPaymentPassViewController` and
/// wiring the SDK's handler closure happens entirely inside the native
/// implementation — see `IdemiaCardBridge.swift`. This is the same principle as
/// `ApiClient` not leaking `DioException`: each layer speaks its own
/// vocabulary, and the translation lives at the seam, not in the caller.
///
/// GENERATED: `lib/core/native/idemia_card_api.g.dart` and
/// `ios/Runner/IdemiaCardApi.g.swift` — regenerate with:
///   dart run pigeon --input pigeons/idemia_card_api.dart
class CardHandleData {
  CardHandleData({
    required this.cardHandle,
    required this.issuerId,
    required this.lastDigits,
    required this.expiry,
    required this.state,
  });

  String cardHandle;

  String issuerId;

  String lastDigits;

  String expiry;

  /// `ACTIVE` / `NOT_ACTIVE` / `SUSPENDED` / `TERMINATED` — kept as the raw
  /// string from the SDK's `CardState`. Decoding into a Dart enum happens on
  /// the Flutter side, in the same mapper that already parses `CardDto.state`,
  /// so there is exactly one place that knows the four values.
  String state;

  List<Object?> _toList() {
    return <Object?>[
      cardHandle,
      issuerId,
      lastDigits,
      expiry,
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static CardHandleData decode(Object result) {
    result as List<Object?>;
    return CardHandleData(
      cardHandle: result[0]! as String,
      issuerId: result[1]! as String,
      lastDigits: result[2]! as String,
      expiry: result[3]! as String,
      state: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CardHandleData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cardHandle, other.cardHandle) && _deepEquals(issuerId, other.issuerId) && _deepEquals(lastDigits, other.lastDigits) && _deepEquals(expiry, other.expiry) && _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CardHandleData(cardHandle: $cardHandle, issuerId: $issuerId, lastDigits: $lastDigits, expiry: $expiry, state: $state)';
  }
}

class ProvisionableCard {
  ProvisionableCard({
    required this.cardReferenceId,
    required this.issuerId,
    required this.lastDigits,
    required this.expiry,
    required this.paymentNetwork,
    required this.displayName,
    required this.eligibilityStatus,
  });

  String cardReferenceId;

  String issuerId;

  String lastDigits;

  String expiry;

  String paymentNetwork;

  String displayName;

  /// One of the SDK's `Eligibility` raw values: `eligible`, `nonEligible`,
  /// `alreadyProvisioned`, `alreadyProvisionedOnPhone`, `alreadyProvisionedOnWatch`.
  String eligibilityStatus;

  List<Object?> _toList() {
    return <Object?>[
      cardReferenceId,
      issuerId,
      lastDigits,
      expiry,
      paymentNetwork,
      displayName,
      eligibilityStatus,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProvisionableCard decode(Object result) {
    result as List<Object?>;
    return ProvisionableCard(
      cardReferenceId: result[0]! as String,
      issuerId: result[1]! as String,
      lastDigits: result[2]! as String,
      expiry: result[3]! as String,
      paymentNetwork: result[4]! as String,
      displayName: result[5]! as String,
      eligibilityStatus: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProvisionableCard || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cardReferenceId, other.cardReferenceId) && _deepEquals(issuerId, other.issuerId) && _deepEquals(lastDigits, other.lastDigits) && _deepEquals(expiry, other.expiry) && _deepEquals(paymentNetwork, other.paymentNetwork) && _deepEquals(displayName, other.displayName) && _deepEquals(eligibilityStatus, other.eligibilityStatus);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ProvisionableCard(cardReferenceId: $cardReferenceId, issuerId: $issuerId, lastDigits: $lastDigits, expiry: $expiry, paymentNetwork: $paymentNetwork, displayName: $displayName, eligibilityStatus: $eligibilityStatus)';
  }
}

/// Everything the bank's backend must supply before provisioning can start.
///
/// Every field here traces to a specific requirement in the bank's technical
/// spec (see the `assetHash`/JWS/certificate walkthrough): the wrapper does no
/// cryptography of its own, it only carries what the backend already signed.
class ProvisioningRequest {
  ProvisioningRequest({
    required this.cardReferenceId,
    required this.certificates,
    required this.nonce,
    required this.nonceSignature,
    required this.userAuthorization,
  });

  String cardReferenceId;

  /// DER-encoded certificate chain, as the SDK's `ProvisioningData.certificates`
  /// expects (`[Data]` on the Swift side).
  List<Uint8List> certificates;

  Uint8List nonce;

  Uint8List nonceSignature;

  /// The JWS token (`enrollAuth`) signed by the bank's backend with its RSA
  /// private key — becomes `ProvisioningData.userAuthorization`.
  String userAuthorization;

  List<Object?> _toList() {
    return <Object?>[
      cardReferenceId,
      certificates,
      nonce,
      nonceSignature,
      userAuthorization,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProvisioningRequest decode(Object result) {
    result as List<Object?>;
    return ProvisioningRequest(
      cardReferenceId: result[0]! as String,
      certificates: (result[1]! as List<Object?>).cast<Uint8List>(),
      nonce: result[2]! as Uint8List,
      nonceSignature: result[3]! as Uint8List,
      userAuthorization: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProvisioningRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cardReferenceId, other.cardReferenceId) && _deepEquals(certificates, other.certificates) && _deepEquals(nonce, other.nonce) && _deepEquals(nonceSignature, other.nonceSignature) && _deepEquals(userAuthorization, other.userAuthorization);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ProvisioningRequest(cardReferenceId: $cardReferenceId, certificates: $certificates, nonce: $nonce, nonceSignature: $nonceSignature, userAuthorization: $userAuthorization)';
  }
}

class ProvisioningResult {
  ProvisioningResult({
    required this.success,
    this.errorCode,
    this.errorMessage,
  });

  bool success;

  /// A code from Appendix A of the bank's spec (`CARD_EXPIRED`, `CARD_LOCKED`,
  /// …) when the SDK or PassKit rejected the request. `null` on success.
  String? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      success,
      errorCode,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProvisioningResult decode(Object result) {
    result as List<Object?>;
    return ProvisioningResult(
      success: result[0]! as bool,
      errorCode: result[1] as String?,
      errorMessage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProvisioningResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) && _deepEquals(errorCode, other.errorCode) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ProvisioningResult(success: $success, errorCode: $errorCode, errorMessage: $errorMessage)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CardHandleData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ProvisionableCard) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ProvisioningRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ProvisioningResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return CardHandleData.decode(readValue(buffer)!);
      case 130:
        return ProvisionableCard.decode(readValue(buffer)!);
      case 131:
        return ProvisioningRequest.decode(readValue(buffer)!);
      case 132:
        return ProvisioningResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Methods Flutter calls; the Swift side implements them.
///
/// `@async` marks a method as `async` on both sides — Pigeon generates a
/// `Future`-returning Dart method backed by a Swift method using completion
/// handlers (or `async`/`await`, matching the SDK's own signatures almost
/// exactly, since the SDK itself is already async-first).
class IdemiaCardHostApi {
  /// Constructor for [IdemiaCardHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IdemiaCardHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<CardHandleData>> findCardsByCardHolder({required String cardHolderHandle, required String issuerId}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.IdemiaCardHostApi.findCardsByCardHolder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[cardHolderHandle, issuerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CardHandleData>();
  }

  Future<List<ProvisionableCard>> checkCards({required String issuerId, required List<String> cardHandles}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.IdemiaCardHostApi.checkCards$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[issuerId, cardHandles]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ProvisionableCard>();
  }

  /// Synchronous in the real SDK (`canAddCards` has no `async` keyword there)
  /// because it only reads local PassKit state — no network round trip, so no
  /// reason to force it through the async machinery on either side.
  Future<Map<String, String>> canAddCards({required List<String> lastDigits}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.IdemiaCardHostApi.canAddCards$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[lastDigits]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, String>();
  }

  /// Presents `PKAddPaymentPassViewController` natively and drives it to
  /// completion. The `Future` resolves only after the user finishes the native
  /// flow (or cancels/fails it) — this single call replaces
  /// `generatePassKitRequestConfiguration` + `startPushProvisioning` +
  /// `notifyProvisioningCompleted` from the raw SDK, because all three only
  /// make sense chained together on the native side.
  Future<ProvisioningResult> startProvisioning(ProvisioningRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.IdemiaCardHostApi.startProvisioning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ProvisioningResult;
  }
}
