// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}



class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Contract for the lifecycle of IDEMIA's `CardSecureDisplay` module (see
/// section 5.2 of the bank's IDEMIA SDK spec).
///
/// ## Why no method here returns the rendered image
///
/// The whole point of `CardSecureDisplay` is that the full PAN/PIN never
/// exists as text or bytes any caller can log, cache, or ship elsewhere.
/// Returning image bytes across this API would put pixel data of a secret
/// value into Dart memory — technically not the PAN as a string, but still
/// a needless copy of sensitive material crossing a boundary that does not
/// need it to cross.
///
/// Instead, rendering happens entirely on the native side, inside a
/// `FlutterPlatformView` (`SecureCardDisplayPlatformView.swift`) that calls
/// `FakeSecureCardDisplayService.getCardDataImage`/`getCardPinImage`
/// directly and shows the result in a native `UIImageView`. Flutter only
/// ever asks for the *view* (via `UiKitView`), never the image data — the
/// same "hand over a native view, not bytes" principle already used for
/// `PKAddPaymentPassViewController` in `IdemiaCardBridge`.
///
/// This file therefore only covers what genuinely needs Dart-side control:
/// the module's lifecycle (`initialize`/`wipe`) and the one method whose
/// result — a system pasteboard write — has no visual representation for a
/// platform view to own.
///
/// GENERATED: `lib/core/native/secure_card_display_api.g.dart` and
/// `ios/Runner/SecureCardDisplayApi.g.swift` — regenerate with:
///   dart run pigeon --input pigeons/secure_card_display_api.dart
class SecureCardDisplayHostApi {
  /// Constructor for [SecureCardDisplayHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SecureCardDisplayHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.SecureCardDisplayHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> isInitialized() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.SecureCardDisplayHostApi.isInitialized$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> copyPanToClipboard({required String cardReferenceId, required double ttlSeconds}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.SecureCardDisplayHostApi.copyPanToClipboard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[cardReferenceId, ttlSeconds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> wipe() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.SecureCardDisplayHostApi.wipe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
