// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// A debug-only channel to the Wallet Extension's logic, called directly by
/// our own UI instead of by the real Apple Wallet.
///
/// This is intentionally a **separate** Pigeon file from `idemia_card_api.dart`:
/// that one describes production API surface (what the app calls to talk to
/// the SDK); this one describes a test harness that will not exist once real
/// device testing with the issuer entitlement is possible. Keeping them apart
/// means deleting the harness later is a two-file removal, not a search for
/// which methods in a shared file were "the real ones."
class ExtensionStatusResult {
  ExtensionStatusResult({
    required this.passEntriesAvailable,
    required this.requiresAuthentication,
    required this.elapsedMicroseconds,
  });

  bool passEntriesAvailable;

  bool requiresAuthentication;

  /// Measured natively, around the exact call the real Wallet times against
  /// its ~100ms budget — see `ExtensionSimulatorBridge.simulateStatus`. Kept
  /// as a plain int rather than a `Duration` because Pigeon has no `Duration`
  /// type; the Dart side converts it back.
  int elapsedMicroseconds;

  List<Object?> _toList() {
    return <Object?>[
      passEntriesAvailable,
      requiresAuthentication,
      elapsedMicroseconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static ExtensionStatusResult decode(Object result) {
    result as List<Object?>;
    return ExtensionStatusResult(
      passEntriesAvailable: result[0]! as bool,
      requiresAuthentication: result[1]! as bool,
      elapsedMicroseconds: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExtensionStatusResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(passEntriesAvailable, other.passEntriesAvailable) && _deepEquals(requiresAuthentication, other.requiresAuthentication) && _deepEquals(elapsedMicroseconds, other.elapsedMicroseconds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExtensionStatusResult(passEntriesAvailable: $passEntriesAvailable, requiresAuthentication: $requiresAuthentication, elapsedMicroseconds: $elapsedMicroseconds)';
  }
}

class PassEntryData {
  PassEntryData({
    required this.cardReferenceId,
    required this.displayName,
  });

  String cardReferenceId;

  String displayName;

  List<Object?> _toList() {
    return <Object?>[
      cardReferenceId,
      displayName,
    ];
  }

  Object encode() {
    return _toList();  }

  static PassEntryData decode(Object result) {
    result as List<Object?>;
    return PassEntryData(
      cardReferenceId: result[0]! as String,
      displayName: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PassEntryData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cardReferenceId, other.cardReferenceId) && _deepEquals(displayName, other.displayName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PassEntryData(cardReferenceId: $cardReferenceId, displayName: $displayName)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ExtensionStatusResult) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is PassEntryData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ExtensionStatusResult.decode(readValue(buffer)!);
      case 130:
        return PassEntryData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class WalletExtensionSimulatorHostApi {
  /// Constructor for [WalletExtensionSimulatorHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WalletExtensionSimulatorHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Instantiates `ServiceProvider` (the same class the real extension uses)
  /// and calls `status(completion:)` directly — a plain method call, not a
  /// system-routed one — timing it the way Wallet's own 100ms budget would.
  Future<ExtensionStatusResult> simulateStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.WalletExtensionSimulatorHostApi.simulateStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ExtensionStatusResult;
  }

  /// `LAContext.evaluatePolicy` with Face ID/Touch ID — the same
  /// authentication gate `requiresAuthentication` would trigger for a real
  /// UI Extension, run here as a plain call from the main app instead of a
  /// second `.appex` process.
  Future<bool> authenticate() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.WalletExtensionSimulatorHostApi.authenticate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Calls `ServiceProvider.passEntries(completion:)` directly, mapping the
  /// resulting `PKIssuerProvisioningExtensionPassEntry` array to plain data.
  Future<List<PassEntryData>> simulatePassEntries() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bank_app_reference.WalletExtensionSimulatorHostApi.simulatePassEntries$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<PassEntryData>();
  }
}
